### PR TITLE
pr-122149

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122149

**Comment by BryanEngler** [comment]
@wcao20170619 ill fix this right now since i broke it

**Comment by BryanEngler** [comment]
running CI here https://github.com/BryanEngler/liferay-portal/pull/664

**Comment by BryanEngler** [comment]
ci:close

**Pull request closed without merging**
