### PR TITLE
LPS-79391 portal-search-admin-web: move "Indexing Actions" from Server Admin to Search Admin

### PR DESCRIPTION
**Pull request by wcao20170619**

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:test

**Comment by wcao20170619** [comment]
ci:test

**Comment by wcao20170619** [comment]
ci:test

**Comment by wcao20170619** [comment]
ci:stop

**Comment by wcao20170619** [comment]
ci:test

**Comment by ericyanLr** [comment]
ci:test

**Pull request closed without merging**
