### PR TITLE
LPS-121369 portal-search-test:add integration tests for SearchResponse.getTook from different searching results.

### PR DESCRIPTION
**Pull request by wcao20170619**

### CODE REVIEW

**Comment by wcao20170619** [comment]
ci:test:sf

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by wcao20170619** [comment]
ci:search:test

**Comment by wcao20170619** [comment]
ci:test:search

**Comment by xbrianlee** [comment]
ci:forward

**Pull request closed without merging**
